// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JFrogVSExtension.UI.WebView
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidToolWindowWebviewPackageString = "b3809bd6-3c53-46c3-8954-d1783d4e5003";
        public static Guid guidToolWindowWebviewPackage = new Guid(guidToolWindowWebviewPackageString);

        public const string guidToolWindowWebviewPackageCmdSetString = "5be44006-2baa-4566-a2f0-fd60015f3620";
        public static Guid guidToolWindowWebviewPackageCmdSet = new Guid(guidToolWindowWebviewPackageCmdSetString);

        public const string guidImagesString = "9ddb7834-8137-4411-a623-6b68b9f7c9bd";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowWebviewCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}