name: Release

on:
  release:
    types: [published]

jobs:

  pre-build:
    name: Update version in source code
    runs-on: windows-latest
    env:
        NEW_VERSION: '${{ github.ref_name }}' 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with: # remove when opening a pr
            ref: add-release-workflow

      - name: Update VSIX Version in manifest file
        run: .\scripts\UpdateVsixVersion.ps1
        shell: pwsh
        
      - name: Commit and push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          branch: ${{ github.ref_name }}
          commit_message: "Updated VSIX version to ${{ env.NEW_VERSION }}"

  call-build-workflow:
      uses: ./.github/workflows/build-vsix.yml
      needs: pre-build
  
  release:
    runs-on: windows-latest
    needs: call-build-workflow
    steps:
      - name: Download VSIX artifact
        uses: actions/download-artifact@v3
        with:
            name: vsix-artifacts
            path: ./JFrogVSExtension/bin/Release

      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JFrogVSExtension/bin/Release/JFrogVSExtension.vsix
          asset_name: JFrogVSExtension.vsix
          asset_content_type: application/octet-stream

        # deploy to marketplace
     # - name: Publish to Visual Studio marketplace
        # run: 